name: CoraxGames
favicon: null
layout_spectrum: 0.7634
typography_spectrum: 0.55506
title: Corax Games
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#15110e'
    - '#c2c1bf'
    - '#969da5'
    - '#dea824'
  brandStrength: 0
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
